# Generated by Django 2.1 on 2018-08-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='collection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='partner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='rewrite_from',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='rewrite_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='warc_match',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='collection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='partner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='rewrite_from',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='rewrite_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='warc_match',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='capture_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='capture_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='policy',
            field=models.CharField(choices=[('block', 'Block playback'), ('message', 'Block playback with message'), ('allow', 'Allow playback'), ('auth', 'Require auth for playback'), ('rewrite', 'Rewrite playback')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='retrieval_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='retrieval_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('surt', 'SURT'), ('surt-neg', 'SURT negation'), ('regex', 'regular expression'), ('daterange', 'date range'), ('warcname', 'WARC name (or regex)'), ('collection', 'collection'), ('partner', 'partner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='seconds_since_capture',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='surt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='capture_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='capture_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='policy',
            field=models.CharField(choices=[('block', 'Block playback'), ('message', 'Block playback with message'), ('allow', 'Allow playback'), ('auth', 'Require auth for playback'), ('rewrite', 'Rewrite playback')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='retrieval_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='retrieval_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='rule_type',
            field=models.CharField(choices=[('surt', 'SURT'), ('surt-neg', 'SURT negation'), ('regex', 'regular expression'), ('daterange', 'date range'), ('warcname', 'WARC name (or regex)'), ('collection', 'collection'), ('partner', 'partner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='seconds_since_capture',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='surt',
            field=models.TextField(blank=True),
        ),
    ]
