# Generated by Django 2.1 on 2018-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_auto_20180813_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='exact_match',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='js_modifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='exact_match',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulechange',
            name='js_modifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='who',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rulechange',
            name='who',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
