# Generated by Django 3.2.6 on 2024-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0014_auto_20211020_2258"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="status_code",
            field=models.IntegerField(
                blank=True,
                help_text="HTTP status code, like 200, 403, 500, to apply this rule to.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rulechange",
            name="status_code",
            field=models.IntegerField(
                blank=True,
                help_text="HTTP status code, like 200, 403, 500, to apply this rule to.",
                null=True,
            ),
        ),
    ]
