# Generated by Django 3.2.6 on 2024-07-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_auto_20240130_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='content_type',
            field=models.TextField(blank=True, help_text='Content-Type, like text/html, image/gif, to apply this rule to.', null=True),
        ),
        migrations.AddField(
            model_name='rulechange',
            name='content_type',
            field=models.TextField(blank=True, help_text='Content-Type, like text/html, image/gif, to apply this rule to.', null=True),
        ),
    ]
